//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrzn41.WebexTeams.ResourceMessage {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thrzn41.WebexTeams.ResourceMessage.ErrorMessages", typeof(ErrorMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on deserializing from Json string: [Line = {0}, Position = {1}, Path = {2}].
        /// </summary>
        internal static string TeamsJsonDeserializationError {
            get {
                return ResourceManager.GetString("TeamsJsonDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on serializing to Json string: [Line = {0}, Position = {1}, Path = {2}].
        /// </summary>
        internal static string TeamsJsonSerializationError {
            get {
                return ResourceManager.GetString("TeamsJsonSerializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisco Webex Teams API Service returned an error..
        /// </summary>
        internal static string TeamsResultError {
            get {
                return ResourceManager.GetString("TeamsResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Version1TeamsResultError {
            get {
                return ResourceManager.GetString("Version1TeamsResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}(ErrorCode:{1}).
        /// </summary>
        internal static string Version1TeamsResultErrorWithCode {
            get {
                return ResourceManager.GetString("Version1TeamsResultErrorWithCode", resourceCulture);
            }
        }
    }
}
